FROM golang:1.20.5-alpine

EXPOSE 8080 4000

WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the application source code
COPY . .

RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

# ENV GO111MODULE=off

# Build the application
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o /app/template-service ./cmd/template-service

ENTRYPOINT [ "/go/bin/dlv", "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--continue", "--api-version=2", "exec", "/app/template-service" ]